correct spelling
yloiseau/watson-utils pull request #1
Opened 2018-12-08 20:31 UTC by corbolais

thanks for the utils! very handy :)

2018-12-17 16:26 UTC, yloiseau requested changes

2018-12-17 16:26 UTC, yloiseau commented on .gitignore
> +tags
This file is specific to some tools that are developer dependent, and thus shouldn't be present here. Please put it in your global `.gitignore`.

2018-12-17 16:27 UTC, yloiseau commented
Thank you for the contribution. Just a minor fix (see review).

2018-12-17 16:29 UTC, corbolais commented
Can fix.

OTOH, I don't see any disadvantage for developers having this line included. It's a [ctags](http://ctags.sourceforge.net/) file (i.e. used w/ a vim plugin or just plain ctags).

2018-12-18 09:07 UTC, yloiseau commented
I know what a ctags file is. My point is that this kind of files, that are specific to the developer's environment (IDE projects, .DS_STORE for Mac users, ...) should be ignored in the global `~/.gitignore` file instead of the local project one. The project `.gitignore` should only contain patterns relevant to the project, i.e. ignoring files produced by the build process and so on. This allows to:
1. keep things DRY by ignoring these files only in one place, and don't repeat the list in every projects you have;
2. don't bloat the project configuration with files or patterns that are not useful to other devs, making it easier to grasp for new comers.

2018-12-18 09:32 UTC, corbolais commented
good argument.
pushed rm commit.

2018-12-18 09:38 UTC, yloiseau approved these changes

2018-12-18 09:38 UTC, merged